@startuml

' () "First Interface"
' () "Another interface" as Interf2
' interface Interf3
' interface "Last\ninterface" as Interf4


skinparam BackgroundColor transparent
skinparam componentStyle uml2

component NoticeManager {


}




  component NoticeCardList {
}
  component BussinessCard {
}

[BussinessCard]->[NoticeCardList]



@enduml
